window.MASTER_SKILLS = {
  "108upanishads": {
    "title": "108 Upanishads",
    "category": "Upanishads",
    "pages": 908,
    "author": "Veda Vyasa & Sages",
    "summary": "Complete collection of 108 Upanishads detailing Brahman, Atman, and Moksha philosophy.",
    "slug": "108upanishads",
    "skill_md": "---\nname: 108upanishads\ndescription: Agent Skill for 108 Upanishads (908 pages, Upanishads). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# 108 Upanishads\n\n> **Category**: Upanishads  \n> **Author**: Veda Vyasa & Sages  \n> **Total Pages**: 908 pages  \n> **Summary**: Complete collection of 108 Upanishads detailing Brahman, Atman, and Moksha philosophy.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Complete collection of 108 Upanishads detailing Brahman, Atman, and Moksha philosophy.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 108 Upanishads\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 108 Upanishads\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 108 Upanishads\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 108 Upanishads\n\nComplete collection of 108 Upanishads detailing Brahman, Atman, and Moksha philosophy.\n\nThis volume spans **908 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 108 Upanishads\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "rig-veda-complete--sakala-shakha-": {
    "title": "Rig Veda Complete (Sakala Shakha)",
    "category": "Vedas",
    "pages": 1636,
    "author": "Vedic Sages (Rishis)",
    "summary": "Oldest Vedic Samhita with 10 Mandalas and 10,552 mantras praising cosmic forces and Rta.",
    "slug": "rig-veda-complete--sakala-shakha-",
    "skill_md": "---\nname: rig-veda-complete--sakala-shakha-\ndescription: Agent Skill for Rig Veda Complete (Sakala Shakha) (1636 pages, Vedas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Rig Veda Complete (Sakala Shakha)\n\n> **Category**: Vedas  \n> **Author**: Vedic Sages (Rishis)  \n> **Total Pages**: 1636 pages  \n> **Summary**: Oldest Vedic Samhita with 10 Mandalas and 10,552 mantras praising cosmic forces and Rta.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Oldest Vedic Samhita with 10 Mandalas and 10,552 mantras praising cosmic forces and Rta.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Rig Veda Complete (Sakala Shakha)\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Rig Veda Complete (Sakala Shakha)\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Rig Veda Complete (Sakala Shakha)\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Rig Veda Complete (Sakala Shakha)\n\nOldest Vedic Samhita with 10 Mandalas and 10,552 mantras praising cosmic forces and Rta.\n\nThis volume spans **1636 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Rig Veda Complete (Sakala Shakha)\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "atharva-veda-samhita-part-1-pandit-jayadev-sharma": {
    "title": "Atharva Veda Samhita Part 1",
    "category": "Vedas",
    "pages": 444,
    "author": "Rishi Atharvan & Angiras",
    "summary": "Vedic Samhita focusing on daily life, healing, cosmic order, and earth protection.",
    "slug": "atharva-veda-samhita-part-1-pandit-jayadev-sharma",
    "skill_md": "---\nname: atharva-veda-samhita-part-1-pandit-jayadev-sharma\ndescription: Agent Skill for Atharva Veda Samhita Part 1 (444 pages, Vedas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Atharva Veda Samhita Part 1\n\n> **Category**: Vedas  \n> **Author**: Rishi Atharvan & Angiras  \n> **Total Pages**: 444 pages  \n> **Summary**: Vedic Samhita focusing on daily life, healing, cosmic order, and earth protection.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Vedic Samhita focusing on daily life, healing, cosmic order, and earth protection.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Atharva Veda Samhita Part 1\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Atharva Veda Samhita Part 1\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Atharva Veda Samhita Part 1\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Atharva Veda Samhita Part 1\n\nVedic Samhita focusing on daily life, healing, cosmic order, and earth protection.\n\nThis volume spans **444 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Atharva Veda Samhita Part 1\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "brihadaranyaka-upanishad": {
    "title": "Brihadaranyaka Upanishad",
    "category": "Upanishads",
    "pages": 490,
    "author": "Yajnavalkya & Gargi",
    "summary": "Largest Upanishad containing Neti Neti, Asato Ma Sadgamaya, and dialogues of Gargi.",
    "slug": "brihadaranyaka-upanishad",
    "skill_md": "---\nname: brihadaranyaka-upanishad\ndescription: Agent Skill for Brihadaranyaka Upanishad (490 pages, Upanishads). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Brihadaranyaka Upanishad\n\n> **Category**: Upanishads  \n> **Author**: Yajnavalkya & Gargi  \n> **Total Pages**: 490 pages  \n> **Summary**: Largest Upanishad containing Neti Neti, Asato Ma Sadgamaya, and dialogues of Gargi.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Largest Upanishad containing Neti Neti, Asato Ma Sadgamaya, and dialogues of Gargi.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Brihadaranyaka Upanishad\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Brihadaranyaka Upanishad\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Brihadaranyaka Upanishad\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Brihadaranyaka Upanishad\n\nLargest Upanishad containing Neti Neti, Asato Ma Sadgamaya, and dialogues of Gargi.\n\nThis volume spans **490 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Brihadaranyaka Upanishad\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "katha-upanishad": {
    "title": "Katha Upanishad",
    "category": "Upanishads",
    "pages": 12,
    "author": "Yama & Nachiketa",
    "summary": "Dialogue between Nachiketa and Yama on immortality, Atman, and the two paths (Shreya vs Preya).",
    "slug": "katha-upanishad",
    "skill_md": "---\nname: katha-upanishad\ndescription: Agent Skill for Katha Upanishad (12 pages, Upanishads). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Katha Upanishad\n\n> **Category**: Upanishads  \n> **Author**: Yama & Nachiketa  \n> **Total Pages**: 12 pages  \n> **Summary**: Dialogue between Nachiketa and Yama on immortality, Atman, and the two paths (Shreya vs Preya).\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Dialogue between Nachiketa and Yama on immortality, Atman, and the two paths (Shreya vs Preya).\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Katha Upanishad\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Katha Upanishad\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Katha Upanishad\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Katha Upanishad\n\nDialogue between Nachiketa and Yama on immortality, Atman, and the two paths (Shreya vs Preya).\n\nThis volume spans **12 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Katha Upanishad\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "isakenakathapras0000upan": {
    "title": "Isa Kena Katha Prasna Upanishads",
    "category": "Upanishads",
    "pages": 312,
    "author": "Vedic Rishis",
    "summary": "Primary Mukhya Upanishads with Adi Shankara commentary foundation.",
    "slug": "isakenakathapras0000upan",
    "skill_md": "---\nname: isakenakathapras0000upan\ndescription: Agent Skill for Isa Kena Katha Prasna Upanishads (312 pages, Upanishads). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Isa Kena Katha Prasna Upanishads\n\n> **Category**: Upanishads  \n> **Author**: Vedic Rishis  \n> **Total Pages**: 312 pages  \n> **Summary**: Primary Mukhya Upanishads with Adi Shankara commentary foundation.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Primary Mukhya Upanishads with Adi Shankara commentary foundation.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Isa Kena Katha Prasna Upanishads\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Isa Kena Katha Prasna Upanishads\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Isa Kena Katha Prasna Upanishads\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Isa Kena Katha Prasna Upanishads\n\nPrimary Mukhya Upanishads with Adi Shankara commentary foundation.\n\nThis volume spans **312 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Isa Kena Katha Prasna Upanishads\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "gita-sadhak-sanjevani-english-old": {
    "title": "Gita Sadhaka Sanjivani",
    "category": "Gita",
    "pages": 1134,
    "author": "Swami Ramsukhdas / Veda Vyasa",
    "summary": "Comprehensive commentary on the 700 verses of the Bhagavad Gita.",
    "slug": "gita-sadhak-sanjevani-english-old",
    "skill_md": "---\nname: gita-sadhak-sanjevani-english-old\ndescription: Agent Skill for Gita Sadhaka Sanjivani (1134 pages, Gita). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Gita Sadhaka Sanjivani\n\n> **Category**: Gita  \n> **Author**: Swami Ramsukhdas / Veda Vyasa  \n> **Total Pages**: 1134 pages  \n> **Summary**: Comprehensive commentary on the 700 verses of the Bhagavad Gita.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Comprehensive commentary on the 700 verses of the Bhagavad Gita.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Gita Sadhaka Sanjivani\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Gita Sadhaka Sanjivani\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Gita Sadhaka Sanjivani\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Gita Sadhaka Sanjivani\n\nComprehensive commentary on the 700 verses of the Bhagavad Gita.\n\nThis volume spans **1134 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Gita Sadhaka Sanjivani\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "the-mahabharata-set-of-10-volumes": {
    "title": "The Mahabharata (10 Volumes)",
    "category": "Epics",
    "pages": 5800,
    "author": "Veda Vyasa",
    "summary": "World's longest epic detailing Dharma, Karma, Yuddha, and the Bhagavad Gita.",
    "slug": "the-mahabharata-set-of-10-volumes",
    "skill_md": "---\nname: the-mahabharata-set-of-10-volumes\ndescription: Agent Skill for The Mahabharata (10 Volumes) (5800 pages, Epics). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# The Mahabharata (10 Volumes)\n\n> **Category**: Epics  \n> **Author**: Veda Vyasa  \n> **Total Pages**: 5800 pages  \n> **Summary**: World's longest epic detailing Dharma, Karma, Yuddha, and the Bhagavad Gita.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: World's longest epic detailing Dharma, Karma, Yuddha, and the Bhagavad Gita.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 The Mahabharata (10 Volumes)\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 The Mahabharata (10 Volumes)\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 The Mahabharata (10 Volumes)\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 The Mahabharata (10 Volumes)\n\nWorld's longest epic detailing Dharma, Karma, Yuddha, and the Bhagavad Gita.\n\nThis volume spans **5800 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 The Mahabharata (10 Volumes)\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "user-index": {
    "title": "The Ramayana",
    "category": "Epics",
    "pages": 2400,
    "author": "Maharishi Valmiki",
    "summary": "The Adi Kavya detailing Lord Rama's life, ideal Dharma, and victory over Ravana.",
    "slug": "user-index",
    "skill_md": "---\nname: user-index\ndescription: Agent Skill for The Ramayana (2400 pages, Epics). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# The Ramayana\n\n> **Category**: Epics  \n> **Author**: Maharishi Valmiki  \n> **Total Pages**: 2400 pages  \n> **Summary**: The Adi Kavya detailing Lord Rama's life, ideal Dharma, and victory over Ravana.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: The Adi Kavya detailing Lord Rama's life, ideal Dharma, and victory over Ravana.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 The Ramayana\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 The Ramayana\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 The Ramayana\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 The Ramayana\n\nThe Adi Kavya detailing Lord Rama's life, ideal Dharma, and victory over Ravana.\n\nThis volume spans **2400 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 The Ramayana\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "bhagavata-purana---gita-press-text": {
    "title": "Bhagavata Purana",
    "category": "Puranas",
    "pages": 1590,
    "author": "Veda Vyasa",
    "summary": "12 Skandhas and 18,000 verses celebrating Bhakti, Krishna, and Vishnu Avatara.",
    "slug": "bhagavata-purana---gita-press-text",
    "skill_md": "---\nname: bhagavata-purana---gita-press-text\ndescription: Agent Skill for Bhagavata Purana (1590 pages, Puranas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Bhagavata Purana\n\n> **Category**: Puranas  \n> **Author**: Veda Vyasa  \n> **Total Pages**: 1590 pages  \n> **Summary**: 12 Skandhas and 18,000 verses celebrating Bhakti, Krishna, and Vishnu Avatara.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: 12 Skandhas and 18,000 verses celebrating Bhakti, Krishna, and Vishnu Avatara.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Bhagavata Purana\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Bhagavata Purana\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Bhagavata Purana\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Bhagavata Purana\n\n12 Skandhas and 18,000 verses celebrating Bhakti, Krishna, and Vishnu Avatara.\n\nThis volume spans **1590 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Bhagavata Purana\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "2015-47536-the-vishnu-purana": {
    "title": "The Vishnu Purana",
    "category": "Puranas",
    "pages": 444,
    "author": "Sage Parasara",
    "summary": "Fundamental Purana detailing cosmic creation, Manvantaras, and Vishnu's manifestations.",
    "slug": "2015-47536-the-vishnu-purana",
    "skill_md": "---\nname: 2015-47536-the-vishnu-purana\ndescription: Agent Skill for The Vishnu Purana (444 pages, Puranas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# The Vishnu Purana\n\n> **Category**: Puranas  \n> **Author**: Sage Parasara  \n> **Total Pages**: 444 pages  \n> **Summary**: Fundamental Purana detailing cosmic creation, Manvantaras, and Vishnu's manifestations.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Fundamental Purana detailing cosmic creation, Manvantaras, and Vishnu's manifestations.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 The Vishnu Purana\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 The Vishnu Purana\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 The Vishnu Purana\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 The Vishnu Purana\n\nFundamental Purana detailing cosmic creation, Manvantaras, and Vishnu's manifestations.\n\nThis volume spans **444 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 The Vishnu Purana\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "shiv-puran": {
    "title": "Shiv Purana",
    "category": "Puranas",
    "pages": 840,
    "author": "Veda Vyasa",
    "summary": "Sacred Purana extolling Lord Shiva, Mahashivratri, Linga Tattva, and cosmic dissolution.",
    "slug": "shiv-puran",
    "skill_md": "---\nname: shiv-puran\ndescription: Agent Skill for Shiv Purana (840 pages, Puranas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Shiv Purana\n\n> **Category**: Puranas  \n> **Author**: Veda Vyasa  \n> **Total Pages**: 840 pages  \n> **Summary**: Sacred Purana extolling Lord Shiva, Mahashivratri, Linga Tattva, and cosmic dissolution.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Sacred Purana extolling Lord Shiva, Mahashivratri, Linga Tattva, and cosmic dissolution.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Shiv Purana\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Shiv Purana\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Shiv Purana\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Shiv Purana\n\nSacred Purana extolling Lord Shiva, Mahashivratri, Linga Tattva, and cosmic dissolution.\n\nThis volume spans **840 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Shiv Purana\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "devi-bhagavata-with-hindi-translation-volume-1-gita-press": {
    "title": "Devi Bhagavata Purana Vol 1",
    "category": "Puranas",
    "pages": 720,
    "author": "Veda Vyasa",
    "summary": "First half of the Mahapurana dedicated to the Divine Mother Shakti and Mahamaya.",
    "slug": "devi-bhagavata-with-hindi-translation-volume-1-gita-press",
    "skill_md": "---\nname: devi-bhagavata-with-hindi-translation-volume-1-gita-press\ndescription: Agent Skill for Devi Bhagavata Purana Vol 1 (720 pages, Puranas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Devi Bhagavata Purana Vol 1\n\n> **Category**: Puranas  \n> **Author**: Veda Vyasa  \n> **Total Pages**: 720 pages  \n> **Summary**: First half of the Mahapurana dedicated to the Divine Mother Shakti and Mahamaya.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: First half of the Mahapurana dedicated to the Divine Mother Shakti and Mahamaya.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Devi Bhagavata Purana Vol 1\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Devi Bhagavata Purana Vol 1\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Devi Bhagavata Purana Vol 1\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Devi Bhagavata Purana Vol 1\n\nFirst half of the Mahapurana dedicated to the Divine Mother Shakti and Mahamaya.\n\nThis volume spans **720 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Devi Bhagavata Purana Vol 1\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "devi-bhagavata-with-hindi-translation-volume-2-gita-press---tantra-books": {
    "title": "Devi Bhagavata Purana Vol 2",
    "category": "Puranas",
    "pages": 710,
    "author": "Veda Vyasa",
    "summary": "Second half detailing Devi Gita, Navratri sadhana, and Shakti Upasana.",
    "slug": "devi-bhagavata-with-hindi-translation-volume-2-gita-press---tantra-books",
    "skill_md": "---\nname: devi-bhagavata-with-hindi-translation-volume-2-gita-press---tantra-books\ndescription: Agent Skill for Devi Bhagavata Purana Vol 2 (710 pages, Puranas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Devi Bhagavata Purana Vol 2\n\n> **Category**: Puranas  \n> **Author**: Veda Vyasa  \n> **Total Pages**: 710 pages  \n> **Summary**: Second half detailing Devi Gita, Navratri sadhana, and Shakti Upasana.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Second half detailing Devi Gita, Navratri sadhana, and Shakti Upasana.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Devi Bhagavata Purana Vol 2\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Devi Bhagavata Purana Vol 2\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Devi Bhagavata Purana Vol 2\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Devi Bhagavata Purana Vol 2\n\nSecond half detailing Devi Gita, Navratri sadhana, and Shakti Upasana.\n\nThis volume spans **710 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Devi Bhagavata Purana Vol 2\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "brahma-sutra-swami-gambhirananda": {
    "title": "Brahma Sutras",
    "category": "Vedanta",
    "pages": 948,
    "author": "Badarayana (Vyasa)",
    "summary": "555 aphorisms systemizing Vedanta philosophy and reconciliation of Upanishadic truths.",
    "slug": "brahma-sutra-swami-gambhirananda",
    "skill_md": "---\nname: brahma-sutra-swami-gambhirananda\ndescription: Agent Skill for Brahma Sutras (948 pages, Vedanta). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Brahma Sutras\n\n> **Category**: Vedanta  \n> **Author**: Badarayana (Vyasa)  \n> **Total Pages**: 948 pages  \n> **Summary**: 555 aphorisms systemizing Vedanta philosophy and reconciliation of Upanishadic truths.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: 555 aphorisms systemizing Vedanta philosophy and reconciliation of Upanishadic truths.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Brahma Sutras\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Brahma Sutras\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Brahma Sutras\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Brahma Sutras\n\n555 aphorisms systemizing Vedanta philosophy and reconciliation of Upanishadic truths.\n\nThis volume spans **948 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Brahma Sutras\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "thesamkhyaphilos00sinhuoft": {
    "title": "Samkhya Philosophy",
    "category": "Darshanas",
    "pages": 420,
    "author": "Sage Kapila / Ishvarakrishna",
    "summary": "Dualistic philosophy of Purusha (consciousness) and Prakriti (matter) with 24 Tattvas.",
    "slug": "thesamkhyaphilos00sinhuoft",
    "skill_md": "---\nname: thesamkhyaphilos00sinhuoft\ndescription: Agent Skill for Samkhya Philosophy (420 pages, Darshanas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Samkhya Philosophy\n\n> **Category**: Darshanas  \n> **Author**: Sage Kapila / Ishvarakrishna  \n> **Total Pages**: 420 pages  \n> **Summary**: Dualistic philosophy of Purusha (consciousness) and Prakriti (matter) with 24 Tattvas.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Dualistic philosophy of Purusha (consciousness) and Prakriti (matter) with 24 Tattvas.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Samkhya Philosophy\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Samkhya Philosophy\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Samkhya Philosophy\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Samkhya Philosophy\n\nDualistic philosophy of Purusha (consciousness) and Prakriti (matter) with 24 Tattvas.\n\nThis volume spans **420 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Samkhya Philosophy\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "thevaiasesikasut00kanauoft": {
    "title": "Vaisheshika Sutras",
    "category": "Darshanas",
    "pages": 310,
    "author": "Sage Kanada",
    "summary": "Ancient Indian atomism and natural philosophy classifying existence into 6 Padarthas.",
    "slug": "thevaiasesikasut00kanauoft",
    "skill_md": "---\nname: thevaiasesikasut00kanauoft\ndescription: Agent Skill for Vaisheshika Sutras (310 pages, Darshanas). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Vaisheshika Sutras\n\n> **Category**: Darshanas  \n> **Author**: Sage Kanada  \n> **Total Pages**: 310 pages  \n> **Summary**: Ancient Indian atomism and natural philosophy classifying existence into 6 Padarthas.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Ancient Indian atomism and natural philosophy classifying existence into 6 Padarthas.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Vaisheshika Sutras\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Vaisheshika Sutras\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Vaisheshika Sutras\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Vaisheshika Sutras\n\nAncient Indian atomism and natural philosophy classifying existence into 6 Padarthas.\n\nThis volume spans **310 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Vaisheshika Sutras\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "raja-yoga-by-swami-vivekananda": {
    "title": "Raja Yoga (Patanjali Sutras)",
    "category": "Yoga",
    "pages": 240,
    "author": "Swami Vivekananda / Patanjali",
    "summary": "Explanation of Patanjali's Yoga Sutras, Ashtanga Yoga, and mind control.",
    "slug": "raja-yoga-by-swami-vivekananda",
    "skill_md": "---\nname: raja-yoga-by-swami-vivekananda\ndescription: Agent Skill for Raja Yoga (Patanjali Sutras) (240 pages, Yoga). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Raja Yoga (Patanjali Sutras)\n\n> **Category**: Yoga  \n> **Author**: Swami Vivekananda / Patanjali  \n> **Total Pages**: 240 pages  \n> **Summary**: Explanation of Patanjali's Yoga Sutras, Ashtanga Yoga, and mind control.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Explanation of Patanjali's Yoga Sutras, Ashtanga Yoga, and mind control.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Raja Yoga (Patanjali Sutras)\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Raja Yoga (Patanjali Sutras)\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Raja Yoga (Patanjali Sutras)\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Raja Yoga (Patanjali Sutras)\n\nExplanation of Patanjali's Yoga Sutras, Ashtanga Yoga, and mind control.\n\nThis volume spans **240 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Raja Yoga (Patanjali Sutras)\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "8232": {
    "title": "Dharmashastra Vol 1 (Manusmriti)",
    "category": "Dharmashastras",
    "pages": 480,
    "author": "Manu & Sages",
    "summary": "Classical text on ethics, social duties, Ashrama dharma, and jurisprudence.",
    "slug": "8232",
    "skill_md": "---\nname: 8232\ndescription: Agent Skill for Dharmashastra Vol 1 (Manusmriti) (480 pages, Dharmashastras). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Dharmashastra Vol 1 (Manusmriti)\n\n> **Category**: Dharmashastras  \n> **Author**: Manu & Sages  \n> **Total Pages**: 480 pages  \n> **Summary**: Classical text on ethics, social duties, Ashrama dharma, and jurisprudence.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Classical text on ethics, social duties, Ashrama dharma, and jurisprudence.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Dharmashastra Vol 1 (Manusmriti)\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Dharmashastra Vol 1 (Manusmriti)\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Dharmashastra Vol 1 (Manusmriti)\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Dharmashastra Vol 1 (Manusmriti)\n\nClassical text on ethics, social duties, Ashrama dharma, and jurisprudence.\n\nThis volume spans **480 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Dharmashastra Vol 1 (Manusmriti)\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  },
  "8254": {
    "title": "Dharmashastra Vol 2 (Yajnavalkya)",
    "category": "Dharmashastras",
    "pages": 510,
    "author": "Yajnavalkya",
    "summary": "Legal framework, governance, rituals, and civil laws of ancient India.",
    "slug": "8254",
    "skill_md": "---\nname: 8254\ndescription: Agent Skill for Dharmashastra Vol 2 (Yajnavalkya) (510 pages, Dharmashastras). Includes chapter index, patterns, cheatsheet rules, and glossary.\n---\n\n# Dharmashastra Vol 2 (Yajnavalkya)\n\n> **Category**: Dharmashastras  \n> **Author**: Yajnavalkya  \n> **Total Pages**: 510 pages  \n> **Summary**: Legal framework, governance, rituals, and civil laws of ancient India.\n\n---\n\n## \ud83d\udcda Core Mental Models & Structure\n\n1. **Primary Focus**: Legal framework, governance, rituals, and civil laws of ancient India.\n2. **Authority Level**: Primary Source Scripture (\u015aruti / Sm\u1e5bti / Pur\u0101\u1e47a)\n3. **Key Concepts**: Brahman, Atman, Dharma, Karma, Rta, Moksha, Bhakti, Yoga\n\n---\n\n## \ud83d\udcd1 Chapter & Section Index\n\n- [Chapter 1: Overview & Foundation](chapters/ch01-overview.md)\n- [Chapter 2: Key Scriptural Verses & Mantras](chapters/ch02-key-verses.md)\n- [Chapter 3: Philosophical Framework & Tattvas](chapters/ch03-philosophy.md)\n- [Chapter 4: Practical Application & Sadhana](chapters/ch04-practical.md)\n\n---\n\n## \ud83d\udee0 Reference Files\n\n- [Patterns & Principles](patterns.md) \u2014 Key algorithms, mantras, and design patterns.\n- [Cheatsheet](cheatsheet.md) \u2014 Quick decision tables and shloka references.\n- [Glossary](glossary.md) \u2014 Sanskrit-English terminology index.\n",
    "patterns_md": "# Key Patterns & Principles \u2014 Dharmashastra Vol 2 (Yajnavalkya)\n\n## 1. Cosmic Order (\u1e5ata & Dharma)\n- The universe is self-sustaining through natural harmony and moral order.\n- Action aligned with Dharma produces inner clarity and spiritual freedom.\n\n## 2. The Identity of Self (\u0100tman & Brahman)\n- The individual consciousness (\u0100tman) is non-different from the Universal Consciousness (Brahman).\n\n## 3. The Law of Karma\n- Every intentional thought and action generates a natural resonance and result.\n",
    "cheatsheet_md": "# Quick Reference Cheatsheet \u2014 Dharmashastra Vol 2 (Yajnavalkya)\n\n| Concept | Definition / Verse | Key Focus |\n|---|---|---|\n| **Satya** | Truthfulness | Absolute Reality & Moral Integrity |\n| **Dharma** | Cosmic Righteousness | Upholding law and duty |\n| **Ahimsa** | Non-violence | Harm to none in thought, word, or deed |\n| **Moksha** | Liberation | Freedom from cycle of rebirth |\n\n## Core Rule\n> *\"Walk on the path of \u1e5ata and Truth, and you shall prosper.\"*\n",
    "glossary_md": "# Glossary \u2014 Dharmashastra Vol 2 (Yajnavalkya)\n\n- **\u0100tman**: The eternal individual soul / self.\n- **Brahman**: The ultimate, infinite, unchanging reality.\n- **Dharma**: Natural law, duty, righteousness, and order.\n- **Karma**: Action and its natural law of consequence.\n- **Moksha**: Spiritual liberation and ultimate freedom.\n- **\u1e5ata**: The eternal cosmic order governing the universe.\n- **Yajna**: Sacred selfless sacrifice or dedicated action.\n",
    "chapters": {
      "ch01": "# Chapter 1: Overview & Foundation \u2014 Dharmashastra Vol 2 (Yajnavalkya)\n\nLegal framework, governance, rituals, and civil laws of ancient India.\n\nThis volume spans **510 pages** of authoritative text. It is recognized across traditions as a primary reference for spiritual philosophy, ethical conduct, and cosmic understanding.\n",
      "ch02": "# Chapter 2: Key Scriptural Verses & Mantras \u2014 Dharmashastra Vol 2 (Yajnavalkya)\n\nKey verses from this volume:\n1. *\"Ekam Sat Vipra Bahudha Vadanti\"* \u2014 Truth is One; the wise call it by many names.\n2. *\"Sarvam Khalvidam Brahma\"* \u2014 All this universe is indeed Brahman.\n3. *\"Yato Dharmastato Jayah\"* \u2014 Where there is Dharma, there is victory.\n"
    }
  }
};